"""
sam2_loader.py — Load SAM2 masks from SECOND-OC mask .npz files.

Generated by generate_sam2_masks_test.py with keys:
    masks:  (N, 512, 512) bool
    scores: (N,) float32
    bboxes: (N, 4) int32
"""
import numpy as np
from pathlib import Path
from config import MASK_T1_DIR, MASK_T2_DIR


def load_sam2_masks(stem: str, time: str = "T1") -> list[dict]:
    """
    Load SAM2 masks for one image.

    Returns list of dicts:
        {"mask": np.ndarray bool (512,512), "score": float, "mask_id": int}
    """
    mask_dir = MASK_T1_DIR if time == "T1" else MASK_T2_DIR
    path = mask_dir / f"{stem}.npz"

    if not path.exists():
        return []

    data   = np.load(path, allow_pickle=False)
    masks  = data["masks"]   # (N, 512, 512) bool
    scores = data["scores"]  # (N,)

    return [
        {"mask": masks[i].astype(bool), "score": float(scores[i]), "mask_id": i}
        for i in range(masks.shape[0])
    ]
